core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('search/', views.search, name='search'),
    path('shoppingcart/', views.shoppingcart, name='shoppingcart'),
    path('tellus/', views.tellus, name='tellus'),
    path('condition/', views.condition, name='condition'),
    path('privacy/', views.privacy, name='privacy'),
    path('serviceterms/', views.serviceterms, name='serviceterms'),
    path('eula/', views.eula, name='eula'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path("logout/", views.logout_request, name="logout"),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

roadready_parts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):  
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from .forms import SignupForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm

def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect('/')

def contact(request):
    return render(request, 'core/contact.html')

def shoppingcart(request):
    return render(request, 'core/shoppingcart.html')

def search(request):
    return render(request, 'core/search.html')

def tellus(request):
    return render(request, 'core/tellus.html')

def condition(request):
    return render(request, 'core/condition.html')

def privacy(request):
    return render(request, 'core/privacy.html')

def serviceterms(request):
    return render(request, 'core/serviceterms.html')

def eula(request):
    return render(request, 'core/eula.html')

def aboutus(request):
    return render(request, 'core/aboutus.html')

core/templates/core/aboutus.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% load static %}

{% block content %}
        
    <div class="flex items-center justify-center p-12">
        <div class="mx-auto w-full max-w-[550px] px-6 py-12 bg-amber-100 rounded-xl">
            <div>
                <h1 class="mb-12 text-2xl text-center">ABOUT THE VENTURE</h1>
            </div>

            <div class="mb-5">
                <img class="rounded-xl" src="{% static 'img/itsme.jpeg' %}">
                <br>
                <h1 class="font-extrabold text-center lg:text-5xl">John McDove</h1><br>

                <p>This is a portfolio project of the ALX Software Engineer Cohort 7 Backend Specialization.</p><br>

                <p>The concept, design, coding, database, functionalities and paraphernalia is solely the efforts of this full-stack develop.</p><br>

                <p>This web application aims to demonstrate the power and ease of django and tailwind css in the development of the backend structure of a website that is responsive, secure and efficient</p><br>

                <p>This was to have been a teamwork portfolio, but the developer chose to go solo to demonstrate his abilities as a potential full-stack developer.</p><br>
                Email: john_illusies@yahoo.com<br>
                Github: illusies@github.com
            </div>
        
        </div>
    </div>
{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>

{% load static %}

<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title class="bg-sky-900">RoadReady Parts</title>
    </head>

    <body>
        <header class="mx-auto container grid grid-cols-4 py-6 px-6 gap-3 flex">
            <div>
                <a href="{% url 'core:index' %}" class="text-3xl font-semibold">RoadReady Parts</a>
            </div>   

            <div class="col-span-2">
                <form>
                    <div class="relative">
                        <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                            <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
                        </div>
                        <input type="search" id="search" class="block w-full p-6 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 " placeholder="Tell us what you are looking for..." required>
                        <a href="{% url 'item:items' %}" class="px-6 py-3 text-lg text-black font-semibold rounded-xl bg-yellow-300 absolute right-2.5 bottom-2.5">Search</a>
                    </div>
                </form>
            </div>
            <div class="relative">
                <a href="{% url 'core:shoppingcart' %}" class="px-6 py-3 text-lg text-white font-semibold rounded-xl bg-sky-900 hover:bg-yellow-300 hover:text-black">Shopping Cart</a>

                {% if request.user.is_authenticated %}
                    <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-sky-900 text-white rounded-xl hover:bg-yellow-300 hover:text-black">Logout</a>
                {% else %}
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-sky-900 text-white rounded-xl hover:bg-yellow-300 hover:text-black">Register</a>
                {% endif %}
            </div>
        </header>
        
        <div class="px-6 py-6">
            {% block content %}{% endblock %}
        </div>

        <!-- Beginning of Footer -->
        <footer class="mx-auto container py-6 px-6 flex justify-between bg-sky-900">
            <div class="w-1/5 align-content:center" >
                <h3 class="mb-5 font-semibold text-yellow-300">Need Help?</h3>
                <a href="{% url 'core:contact' %}" class="px-6 py-3 text-lg font-semibold bg-sky-900 text-white rounded-xl hover:bg-yellow-300 hover:text-black">Contact Us</a>
                <br><br>
                <img class="w-2/3" src="{% static 'img/holberton-logo.webp' %}" alt="holberton-logo">
            </div>

            <div class="w-1/5">
                <h3 class="mb-5 font-semibold text-yellow-300">Security and Privacy</h3>

                <ul class="space-7-2">
                    <li><a href="{% url 'core:condition' %}" class="text-lg text-amber-100">Conditions of Use</a></li>
                    <li><a href="{% url 'core:privacy' %}" class="text-lg text-amber-100">Privacy Notice</a></li>
                    <li><a href="{% url 'core:serviceterms' %}" class="text-lg text-amber-100">Terms of Service</a></li>
                    <li><a href="{% url 'core:eula' %}" class="text-lg text-amber-100">User Agreement</a></li>
                </ul>
            </div>

            <div class="w-1/5">
                <h3 class="mb-5 font-semibold text-yellow-300">Corporate Info</h3>

                <ul class="space-7-2">
                    <li><a href="{% url 'core:aboutus' %}" class="text-lg text-amber-100">About Us</a></li>
                    <li><a href="{% url 'core:aboutus' %}" class="text-lg text-amber-100">Trademarks</a></li>
                    <li><a href="{% url 'core:aboutus' %}" class="text-lg text-amber-100">FAQs</a></li>
                    <li><a href="{% url 'core:aboutus' %}" class="text-lg text-amber-100">Site Map</a></li>
                </ul>
            </div>

            <div class="w-1/5">
                <h3 class="mb-5 font-semibold text-yellow-300">Customer Service</h3>

                <ul class="space-7-2">
                    <li><a href="#" class="text-lg text-amber-100">Gift Cards</a></li>
                    <li><a href="#" class="text-lg text-amber-100">Your Orders</a></li>
                    <li><a href="#" class="text-lg text-amber-100">Your Payments</a></li>
                </ul>
            </div>

            <div class="w-1/5">
                <h3 class="mb-5 font-semibold text-yellow-300">Location</h3>

                <ul class="space-7-2">
                    <li><a href="https://www.facebook.com" class="text-lg text-amber-100">Facebook</a></li>
                    <li><a href="https://twitter.com" class="text-lg text-amber-100">Twitter</a></li>
                    <li><a href="https://www.instagram.com" class="text-lg text-amber-100">Instagram</a></li>
                    <li><a href="https://www.youtube.com" class="text-lg text-amber-100">Youtube</a></li>
                    <li><a href="https://www.linkedin.com" class="text-lg text-amber-100">LinkedIn</a></li>
                </ul>
                
            </div>
        </footer>
        <!-- End of Footer -->
    </body>
</html>

core/templates/core/condition.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
        
    <div class="flex items-center justify-center p-12">
        <div class="mx-auto w-full max-w-[550px] px-6 py-12 bg-amber-100 rounded-xl">
            <div>
                <h1 class="mb-12 text-2xl text-center">CONDITION OF USE</h1>
            </div>

            <div class="mb-5">
                <p>
                    Last updated: [June 16, 2023]<br><br>

                    By accessing or using the RoadReady Parts website ("Website"), you agree to comply with the following conditions of use. If you do not agree to these conditions, you may not access or use the Website.<br><br>

                    <ol class="space-y-4 list-decimal list-inside">
                        <li>Acceptable Use
                            <ul class="pl-5 mt-2 space-y-1 list-disc list-inside">
                                <li>You shall use the Website solely for lawful purposes and in accordance with applicable laws, regulations, and this Condition of Use.</li>
                                <li>You shall not engage in any activity that may disrupt or interfere with the functioning of the Website or its associated systems.</li>
                            </ul>
                        </li>
                        <li>User Account
                            <ul class="pl-5 mt-2 space-y-1 list-disc list-inside">
                                <li>If you create an account on the Website, you are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.</li>
                                <li>You shall provide accurate and up-to-date information when creating an account and keep your account information current.</li>
                            </ul>
                        </li>
                        <li>Prohibited Activities
                            <ul>
                                <li>You shall not engage in any of the following activities while using the Website:
                                    <ul class="pl-5 mt-2 space-y-1 list-disc list-inside">
                                        <li>Violate any applicable laws, regulations, or third-party rights.</li>
                                        <li>Upload or transmit any content that is illegal, offensive, discriminatory, or infringes upon intellectual property rights.</li>
                                        <li>Introduce viruses, malware, or any other malicious code that may harm or disrupt the Website or its users.</li>
                                        <li>Attempt to gain unauthorized access to the Website or its associated systems.</li>
                                        <li>Engage in any form of data mining, scraping, or extraction of information from the Website.</li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li>Intellectual Property
                            <ul>
                                <li>The Website and its content, including but not limited to text, images, logos, and trademarks, are owned by RoadReady Parts and are protected by intellectual property laws. You shall not reproduce, modify, distribute, or use any of the Website's content without prior written permission from RoadReady Parts.</li>
                            </ul>
                        </li>
                        <li>Disclaimer of Liability
                            <ul>
                                <li>The Website is provided on an "as is" basis. RoadReady Parts disclaims any liability for any damages or losses arising from the use of the Website or its content. While we strive to provide accurate and up-to-date information, we do not warrant the completeness, accuracy, or reliability of the information on the Website.</li>
                            </ul>
                        </li>
                        <li>Modifications to the Website
                            <ul>
                                <li>RoadReady Parts reserves the right to modify, suspend, or discontinue the Website at any time without prior notice. We may also update or change the content or features of the Website. RoadReady Parts shall not be liable for any consequences arising from such modifications or interruptions.</li>
                            </ul>
                        </li>
                        <li>Third-Party Links
                            <ul>
                                <li>The Website may contain links to third-party websites. RoadReady Parts does not endorse or have control over the content, policies, or practices of these third-party websites. Your interactions with such websites are subject to their respective terms and conditions.</li>
                            </ul>
                        </li>
                        <li>Governing Law and Jurisdiction
                            <ul>
                                <li>This Condition of Use shall be governed by and construed in accordance with the laws of [Jurisdiction], without regard to its conflict of law provisions. Any dispute arising out of or relating to this Condition of Use shall be subject to the exclusive jurisdiction of the courts located in [Jurisdiction].</li>
                            </ul>
                        </li>
                        <li>Severability
                            <ul>
                                <li>If any provision of this Condition of Use is found to be invalid, illegal, or unenforceable, the remaining provisions shall continue in full force and effect.</li>
                            </ul>
                        </li>
                        <li>Contact Us
                            <ul>
                                <li>If you have any questions or concerns regarding this Condition of Use, please contact us at [contact information].</li>
                            </ul>
                        </li>
                    </ol>
                </p>
            </div>
        
        </div>
    </div>
{% endblock %}

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
        
    <div class="flex items-center justify-center p-12">
        <div class="mx-auto w-full max-w-[550px] px-6 py-12 bg-amber-100 rounded-xl">
            <div>
                <h1 class="mb-12 text-2xl text-center">Contact Us</h1>
            </div>
            
            <form>
            <div class="mb-5">
                <label
                for="name"
                class="mb-3 block text-base font-medium text-[#07074D]"
                >
                Full Name
                </label>
                <input
                type="text"
                name="name"
                id="name"
                placeholder="Full Name"
                class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                />
            </div>
            <div class="mb-5">
                <label
                for="email"
                class="mb-3 block text-base font-medium text-[#07074D]"
                >
                Email Address
                </label>
                <input
                type="email"
                name="email"
                id="email"
                placeholder="example@domain.com"
                class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                />
            </div>
            <div class="mb-5">
                <label
                for="subject"
                class="mb-3 block text-base font-medium text-[#07074D]"
                >
                Subject
                </label>
                <input
                type="text"
                name="subject"
                id="subject"
                placeholder="Enter your subject"
                class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                />
            </div>
            <div class="mb-5">
                <label
                for="message"
                class="mb-3 block text-base font-medium text-[#07074D]"
                >
                Message
                </label>
                <textarea
                rows="4"
                name="message"
                id="message"
                placeholder="Type your message"
                class="w-full resize-none rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                ></textarea>
            </div>
            <div>
                <button
                class="px-6 py-3 text-lg text-white font-semibold rounded-xl bg-sky-900 hover:bg-yellow-300 hover:text-black"
                >
                Submit
                </button>
            </div>
            </form>
        </div>
    </div>
{% endblock %}

core/templates/core/eula.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
        
    <div class="flex items-center justify-center p-12">
        <div class="mx-auto w-full max-w-[550px] px-6 py-12 bg-amber-100 rounded-xl">
            <div>
                <h1 class="mb-12 text-2xl text-center">END-USER LICENSE AGREEMENT (EULA)</h1>
            </div>

            <div class="mb-5">
                <p>
                    Last updated: [June 16, 2023]<br><br>

                    This End-User License Agreement ("Agreement") is a legal agreement between you ("User") and RoadReady Parts ("Company") regarding the use of the RoadReady Parts website ("Website").<br><br>

                    By accessing or using the Website, you agree to be bound by the terms and conditions of this Agreement. If you do not agree to these terms and conditions, you may not access or use the Website.<br><br>

                    License Grant<br><br>
                    Subject to the terms and conditions of this Agreement, Company grants User a limited, non-exclusive, non-transferable, revocable license to access and use the Website for personal, non-commercial purposes.<br><br>

                    Restrictions<br><br>
                    User agrees not to:
                    <ol class="space-y-4 list-decimal list-inside">
                        <li>Modify, adapt, translate, or create derivative works based on the Website;</li>
                        <li>Reverse engineer, decompile, disassemble, or attempt to discover the source code of the Website;</li>
                        <li>Remove, alter, or obscure any proprietary notices, labels, or marks from the Website;</li>
                        <li>Use the Website for any unlawful or unauthorized purpose;</li>
                        <li>Violate any applicable laws, regulations, or third-party rights.</li>
                    </ol>

                    <br>Intellectual Property<br><br>
                    The Website and its original content, features, and functionality are owned by Company and are protected by international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.<br><br>

                    Disclaimer of Warranty<br><br>
                    The Website is provided on an "as is" basis, without warranties of any kind, either express or implied. Company disclaims all warranties, including, but not limited to, the implied warranties of merchantability, fitness for a particular purpose, and non-infringement. Company does not warrant that the Website will be error-free, uninterrupted, secure, or free of viruses or other harmful components.<br><br>

                    Limitation of Liability<br><br>
                    In no event shall Company be liable for any direct, indirect, incidental, consequential, special, or exemplary damages arising out of or in connection with the use or inability to use the Website or the contents thereof, even if Company has been advised of the possibility of such damages. User's sole remedy is to discontinue using the Website.<br><br>

                    Indemnification<br><br>
                    User agrees to indemnify and hold harmless Company, its affiliates, officers, directors, employees, agents, and licensors from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees arising out of or relating to User's violation of this Agreement or use of the Website.<br><br>

                    Termination<br><br>
                    Company may terminate this Agreement at any time without notice if User breaches any provision of this Agreement. Upon termination, User must cease all use of the Website.<br><br>

                    Governing Law and Jurisdiction<br><br>
                    This Agreement shall be governed by and construed in accordance with the laws of [Jurisdiction], without regard to its conflict of law provisions. Any dispute arising out of or relating to this Agreement shall be subject to the exclusive jurisdiction of the courts located in [Jurisdiction].<br><br>

                    Entire Agreement<br><br>
                    This Agreement constitutes the entire agreement between User and Company regarding the use of the Website and supersedes all prior agreements and understandings.<br><br>

                    Contact Us<br><br>
                    If you have any questions or concerns about this Agreement, please contact us at [contact information].             
                </p>
            </div>
        
        </div>
    </div>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}{% endblock %}

{% load static %}

{% block content %}
    <div class="mx-auto container grid grid-cols-2 gap-3">
        <div>
            <h1 class="font-extrabold lg:text-6xl leading-tight xl:leading-snug text-right">Rev up your ride with</h1>
            <h1 class="font-extrabold lg:text-8xl leading-tight xl:leading-snug text-right">RoadReady</h1>
            <h1 class="font-extrabold lg:text-8xl leading-tight xl:leading-snug text-right">Parts!</h1>
            <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-sky-900 text-white rounded-xl hover:bg-yellow-300 hover:text-black">Login</a>
            <a href="{% url 'core:tellus' %}" class="px-6 py-3 text-lg font-semibold bg-sky-900 text-white rounded-xl hover:bg-yellow-300 hover:text-black">Tell Us</a>
        </div>

        <div class="flex justify-center items-center">
            <img src="{% static 'img/car-parts-pieces.jpg' %}" alt="Seasonal Auto Parts">
        </div>
    </div>

    <!-- Frequently Searched Section -->
    <div class="mx-auto container grid grid-cols-4 gap-3 mt-6 px-6 py-12 bg-amber-100 rounded-xl">
        <div class="p-6 bg-white rounded-b-xl">
            
            <h2 class="mb-12 text-2xl text-center">New <br> Products</h2>
            <img class="w-full" src="{% static 'img/car-alarm-system.jpg' %}" alt="New Products">
        </div>
        <div class="p-6 bg-white rounded-b-xl">
            <h2 class="mb-12 text-2xl text-center">Seasonal <br> items</h2>
            <img class="w-full" src="{% static 'img/seasonal_autoparts.jpg' %}" alt="Seasonal Auto Parts">
        </div>
        <div class="p-6 bg-white rounded-b-xl">
            <h2 class="mb-12 text-2xl text-center">Best <br> Brands</h2>
            <img class="w-full" src="{% static 'img/car-logos.jpg' %}" alt="Car logos">
        </div>
        <div class="p-6 bg-white rounded-b-xl">
            <h2 class="mb-12 text-2xl text-center">Categories</h2>
            <img class="w-full" src="{% static 'img/car-trio.jpg' %}" alt="Three Cars">
        </div>
    </div>
    
    <!-- Frequently Searched Section -->
    <div class="mx-auto container mt-6 px-6 py-12 bg-amber-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Frequently Searched</h2>

        <div class="grid grid-cols-3 gap-3">
            <div class="p-6 bg-white rounded-b-xl">
                <img class="w-full" src="{% static 'img/booster-cables.jpg' %}" alt="Three Cars">
                <h2 class="mb-12 text-2xl text-center">Booster Cables</h2>
            </div>
            <div class="p-6 bg-white rounded-b-xl">
                <img class="w-full" src="{% static 'img/toyota-corolla-2023-headlight.jpg' %}" alt="Three Cars">
                <h2 class="mb-12 text-2xl text-center">Headlight</h2>
            </div>
            <div class="p-6 bg-white rounded-b-xl">
                <img class="w-full" src="{% static 'img/car-inverter.webp' %}" alt="Three Cars">
                <h2 class="mb-12 text-2xl text-center">Inverter</h2>
            </div>
        </div>
    </div>

    <!-- Category Highlights Section -->
    <div class="mx-auto container mt-6 px-6 py-12 bg-amber-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Category Highlights</h2>

        <div class="grid grid-cols-6 gap-3">
          
           
            <div class="p-6 bg-white rounded-b-xl">
                <h2 class="mb-12 text-2xl text-center">Auto<br>Accessories</h2>
                <img class="w-full" src="{% static 'img/ABS sensor.webp' %}" alt="Car logos">
            </div>
            <div class="p-6 bg-white rounded-b-xl">
                <h2 class="mb-12 text-2xl text-center">Auto<br>Parts</h2>
                <img class="w-full" src="{% static 'img/automotive-4pin-relay.jpg' %}" alt="Car logos">
            </div>
            <div class="p-6 bg-white rounded-b-xl">
                <h2 class="mb-12 text-2xl text-center">Auto Repair<br>and Decoration</h2>
                <img class="w-full" src="{% static 'img/car-mat.jpg' %}" alt="Car logos">
            </div>
            <div class="p-6 bg-white rounded-b-xl">
                <h2 class="mb-12 text-2xl text-center">Auto<br>Safety</h2>
                <img class="w-full" src="{% static 'img/car-reverse-camera.jpg' %}" alt="Car logos">
            </div>
            <div class="p-6 bg-white rounded-b-xl">
                <h2 class="mb-12 text-2xl text-center">Motorcycle<br>and Bicycle</h2>
                <img class="w-full" src="{% static 'img/helmet.webp' %}" alt="Car logos">
            </div>
            <div class="p-6 bg-white rounded-b-xl">
                <h2 class="mb-12 text-2xl text-center">Related<br>Products</h2>
                <img class="w-full" src="{% static 'img/car-air-purifier.jpg' %}" alt="Car logos">
            </div>
           

        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log In{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-amber-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Login</h1>

        <form method="post" action=".">
            {% csrf_token %}

            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password }}
            </div>

            {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
            {% endif %}

            <button class="px-8 py-4 text-lg bg-sky-900 text-white rounded-xl hover:bg-yellow-300 hover:text-black">Submit</button>
        </form>
    </div>
{% endblock %}